### ISSUE TITLE
Api Microsoft login question

### ISSUE THREAD

**Issue by LBY-L** [mindstorm38/portablemc#151]
#### Ok, I'll put the things I don't understand:
- How to make the Azure app
- Uri redirects (And what is a uri?)
- How to integrate this to the launch script

Your help will be very useful!

**Comment by mindstorm38** [comment]
I'll answer soon because honestly I don't remember (it's simple, but I need to find)!

**Comment by mindstorm38** [comment]
So, goto https://portal.azure.com/, then "Azure Active Directory", then (in left pane) "App Registrations".

Once you're on this page, you can click "New registration" and enter the redirect URI or "Web" type (URI is a more abstract kind of URL, but you can still put an URI into it). For the launcher, I use something like "localhost:XXXX" because I use a
