### ISSUE TITLE
add a -P (--password) authentication command

### ISSUE THREAD

**Issue by jugendhausldbg** [mindstorm38/portablemc#21]
could you add a --password command for login? 
would be great to have automatic starters.

i had a look in your code if i could add it myself, and if you have no time for that i will do and try so later this year.

**Comment by mindstorm38** [comment]
I had already thought about it, but not knowing if it was the right solution. In fact, once the password was validated once, the session is saved for a limited time and the password is no longer required. Because of that, the argument will rarely be used. Another problem for me is that the password will be readable from any process manager or even in the user's terminal history. Finally, this argument would be impossible to implement for Microsoft authentication.

**Comment by mindstorm38** [comment]
If you can develop, that interests me anyway! The launcher is open for suggestion, do not hesitate.
