### ISSUE TITLE
Support for Babric

### ISSUE THREAD

**Issue by Johan-Mi** [mindstorm38/portablemc#219]
There is a beta fork of Fabric called [Babric](https://babric.github.io/). Its files are hosted on a [different URL](https://maven.glass-launcher.net/#/) than Fabric but the overall structure and functionality seem about the same. Because of this, it should just be a matter of making a copy of the PortableMC-Fabric module with the correct URL, but when I tried this I ran into URL redirect limit errors.

I know that this is quite a niche feature, but I would really appreciate it. Thanks!

**Comment by mindstorm38** [comment]
This is definitely a good idea, as long as it is supported for some time. With the increasing number of loaders natively available, I really need to rework the prefix thing because there are too much arguments like this and they are really not used that much. Maybe a generic argument for the version directory would be fine.

**Comment by mindstorm38** [comment]
The infinite redirect was an issue with PMC bulk download, fixed.

**Comment by mindstorm38** [comment]
Implemented in 4.4.0, if any issue with it please open a new issue
