### ISSUE TITLE
Launching error + Asking for permission

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#28]
I don't get this problem but my friend did when they try to launch. The error line:
`Error: Could not find or load main class net.fabricmc.loader.launch.knot.KnotClient`
`Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.launch.knot.KnotClient`

**Comment by mindstorm38** [comment]
I've seen this error before, but I could not remember how and when. 

Could you provide more information about your friend's installation of the launcher, and what is the command line used here?

**Comment by GoodDay360** [comment]
@mindstorm38 I just use normal command line: `start fabric:1.17.1`. But I already found why it happened. The problem is PMC script isn't download/install Java properly. I fixed this by change Java path.

**Comment by GoodDay360** [comment]
@mindstorm38 Anyway can u add a way to input the account password in start command instead of input it after the command start started ?

**Comment by mindstorm38** [comment]
You can use this launcher in anything you want as long as you mention the use of the project!

For the password in the command line, I already rejected the suggestion from another one because it seemed too risky to me. Process command lines can be seen by anybody with sufficient privileges on a computer, and this would leak your password to any administrator. Also, this feature will not work with Microsoft because you need in this case to input the password in a web browser.

***However***, I understand why this feature can be useful for scripts that want to use PMC, so I'm open to suggestions if you have any idea how to securely transfer a password to the launcher.

**Comment by GoodDay360** [comment]
I did know a way. Since I use pyqt to make UI there is a way that allow user to input password field and blur so user can't see their password. (For Mojang account). But for Microsoft account I'm okay with it since it need to be login in webbrowser.

**Comment by mindstorm38** [comment]
How are you calling PMC in you launcher?

**Comment by GoodDay360** [comment]
@mindstorm38 I convert your PMC into .exe and use subprocess to start comment like: `loader.exe start fabric:{version} -u {username} -jvm...`

**Comment by mindstorm38** [comment]
The fact that you blur the password on the UI side doesn't prevent the password from being leaked, because when you run the sub process, the entire command line is stored by the system. As you can see in the following screenshot, you can see the command line of the Minecraft process by querying the system (the command to do that is `Get-WmiObject Win32_Process -Filter "name = 'javaw.exe'"` on powershell). The most secure way might be to send the password to the process input (`stdin`).

![image](https://user-images.githubusercontent.com/17071361/130315646-92b412ba-7ca9-4a78-9efc-7d49fa18024c.png)

**Comment by mindstorm38** [comment]
To do that you can use `Popen` with `communicate`, you can put the password (with a line return character at the end) in the input. If the launcher ask for the password, the input will be used as far as I know.

**Comment by GoodDay360** [comment]
What you mean is there a way to auto input the password once PMC is asking for password ? I just want to make user easily put password in UI and transfer it to PMC.

**Comment by mindstorm38** [comment]
Yes that's it, you can give an input to the process, and it can be the password (don't forget the line return character, `\n`, it actually "enter" the password). I guess you're are currently using `subprocess.run`, to send an input you just have to use `subprocess.Popen` and then call `communicate` on the Popen object (check subprocess module documentation).

**Comment by GoodDay360** [comment]
@mindstorm38 Thanks. I managed to make it work.

**Comment by mindstorm38** [comment]
I close the issue for now, if you are stuck again comment here!
