### ISSUE TITLE
Make it auto fix java when it fail to load Java

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#33]
![image](https://user-images.githubusercontent.com/59399625/132269751-c8ef1c06-3315-469d-8f59-95f12efd585a.png)
![image](https://user-images.githubusercontent.com/59399625/132269763-0dad147c-1c06-47bc-a38f-192ef34b2666.png)

**Comment by GoodDay360** [comment]
There're more btw.

**Comment by mindstorm38** [comment]
Thank you for the report! Could you put a screenshot of the contents of the directory `.minecraft/jvm/jre-legacy/` and `.minecraft/jvm/java-runtime-alpha/`?

**Comment by mindstorm38** [comment]
I guess that happened after you interrupted a download before its end?

I'll work on that issue, this is not simple since checking the whole JVM directory before starting will increase start time. I already do that for game assets, this works fine but takes time!

**Comment by GoodDay360** [comment]
Kinda something like that. But on most PC their Java is weird it is not just they interrupted a download. The way their Java setup is different from what your Launcher expected.

**Comment by mindstorm38** [comment]
You are talking about local installation, but by default the launcher downloads a custom JVM distributed by Mojang. In this case, if this is not working, it must be because the launcher was interrupted when downloading. If the launcher was not interrupted and the JVM installation doesn't work, there is an issue with the internal launcher's behavior.

In your first message, it's clear that the download was interrupted because the `jvm.cfg` is missing.

Anyway, I will work on an integrity checker for the JVM installation.

**Comment by mindstorm38** [comment]
Available in the next release 2.0.4
