### ISSUE TITLE
Yggdrasil session data not being loaded 

### ISSUE THREAD

**Issue by Ristovski** [mindstorm38/portablemc#49]
Version 2.0.6 does not seem to load the saved session data with yggdrasil auth:
```
$ python3 ./portablemc.py login [redacted]
[  ..  ] Authenticating [redacted] with Mojang...
         Password: 
[  OK  ] Logged in
```
```
$ python3 ./portablemc.py show auth
┌──────┬───────┬──────────┬──────┐
│ Type │ Email │ Username │ UUID │
├──────┼───────┼──────────┼──────┤
└──────┴───────┴──────────┴──────┘
```
however, `portablemc_auth.json` does get created:
```
~/.minecraft $ cat portablemc_auth.json 
{
  "client_id": "[redacted]",
  "yggdrasil": {
    "sessions": {
      "[redacted]": {
        "access_token": "[redacted]",
        "username": "Ristovski",
        "uuid": "[redacted]",
        "client_id": "[redacted]"
      }
    }
  }
}
```

This causes a password prompt to pop up on every launch.
The `logout` command also states that there is currently no session.

**Comment by mindstorm38** [comment]
Thanks for the feedback, I check this soon

**Comment by mindstorm38** [comment]
I don't know why this happens, there must be an issue with the database loading. It seems that you are using the "single file" version of portablemc, so to help me I suggest you to add the following lines at line 1037 (replacing the `pass` keyword):
```
import traceback
traceback.print_exc()
```

This is a terrible design to just ignore exceptions, I will change this in next release to, at least, show a message if loading fails (I hope that's your problem, because if this doesn't come from this I don't know why this doesn't work).

**Comment by Ristovski** [comment]
You were right!
```
Traceback (most recent call last):
  File "./portablemc.py", line 1031, in load
    sess_type.fix_data(sess_data)
  File "./portablemc.py", line 767, in fix_data
    client_token = data.pop("client_token")
KeyError: 'client_token'
```

**Comment by Ristovski** [comment]
Commenting out
```python
# Use class method fix_data to migrate data from older versions of the auth database.
sess_type.fix_data(sess_data)
```
fixes the issue.

**Comment by mindstorm38** [comment]
Ok, that was not what I expected but ok I will fix that! I know what's happening.
