### ISSUE TITLE
Example for API Documents

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#54]
Can you give at least one example for each functions in API Documents to make it easy to understand? 
I have been reading it for a while. I still don't know where to begin.

**Comment by mindstorm38** [comment]
I will :)
It's not that simple for Microsoft auth but for all other classes it should be feasible!

**Comment by mindstorm38** [comment]
Let me know what do you think of these examples!

**Comment by GoodDay360** [comment]
Some parts are still confused like: `Authing both Mojang/Microsoft` and `JVM args`.
I guess to make it easier to use. Maybe you make it into the start option.
```
start_opts = StartOptions()
start_opts.jvmargs = "xmx2G..."
start_opts.authmojang = (email,password)
start_opts.authmicrosoft = (email) #when game function call open webpage and login like when using PMC
```

Rise error when user put username and auth into start options.

**Comment by mindstorm38** [comment]
I added how to change arguments to the documentation. 

For the authentication part, it's not how I would do that because what happen if both `authmojang` and `authmicrosoft` are set, together with `username` and `uuid`. Which will get the priority, it's why I chose to have only one argument `auth_session` and the user decides what type of session to use. I made something like you suggested in the past and this was really hard to maintain or simply got it to work. 

For now, I only documented Yggdrasil sessions because Microsoft ones are really hard to automate, for example in the CLI there is a minimal web server that is opened temporarily to captures tokens answered by Microsoft, maybe I can move this little web server utility to the API to help devs to support Microsoft auth.

**Comment by GoodDay360** [comment]
Yggdrasil sessions is Mojang Auth..?

**Comment by mindstorm38** [comment]
Yes, it's te name of the service

**Comment by GoodDay360** [comment]
Anyway, what is AuthDB?
Does it act as a place to save user information or something? 
What does it have to do with Yggdrasil?

**Comment by GoodDay360** [comment]
Overall can you just give me the simplest example for:
1. Start Minecraft (any version) with Mojang Account
2. Start Minecraft (any version) with Microsoft Account

**Comment by mindstorm38** [comment]
The authentication database is not directly related to Yggdrasil or Microsoft auths, it's a JSON file database where you store auth session **once** you've logged in, so you don't have to relogin on each start.

I can make an example for Mojang account but microsoft ones are harder, but I will try. If you can `install(jvm=True)` like the example in API.md it should install JVM

**Comment by GoodDay360** [comment]
Oh I understood. Anyway I just reinstall my window and noticed that when downloading Minecraft using PMC is so slow it use only 30%->40% of my internet speed.

**Comment by mindstorm38** [comment]
I already made huge improvements to the download API, but it is very complicated to get high performance downloads. It can also be limited by the CDN server

**Comment by GoodDay360** [comment]
I guess you can do multi download process. Like, get all the files list. Split it into half. Start a thread one for download in the first half. Another thread downloads the second half. I don't know if it is possible or not.

**Comment by GoodDay360** [comment]
And one more thing. Since the updated version of patched log4j. When I compile PMC with my launcher it window defender doing flag mark as a virus. I tried to compile without PMC it works find except with PMC 🤷‍♂️.

**Comment by mindstorm38** [comment]
For the parallel download, yes it's how I would do that, but I was wondering if the GIL (global interpreter lock) could slow the download down. But because it's an IO operation, it might be ok, maybe.

For windows defender, I don't know at all how it is supposed to detect viruses, there's nothing in that code that directly refers to the log4j exploit. The only thing that might be detected can be the parts in the file where you can find `<XMLLayout />` and `<LegacyXMLLayout />`.
