### ISSUE TITLE
Cannot start Fabric via API

### ISSUE THREAD

**Issue by drrate** [mindstorm38/portablemc#65]
Hello, I'm currently writing some code for not much reason, and it seems I cannot start Fabric from the API. Is there a way to do this?

**Comment by mindstorm38** [comment]
It's not possible to start fabric from the core API, it is currently only implemented as an add-on to the CLI. However it's an interesting question because I would like to allow others to only extends the API. One possible solution would be to provides add-ons via pip, which provides both an API and a CLI add-on.
