### ISSUE TITLE
Suggestion: Add password argument

### ISSUE THREAD

**Issue by sitapea1337** [mindstorm38/portablemc#69]
Hello!

I'm pretty sure this has been suggested before, but I don't understand why not implemented.
Please add password argument.

Yes, I know this might be a security issue, but still make it users decision not technical restriction.
Thanks!

**Comment by mindstorm38** [comment]
Hi, it was not a limitation in the past, and I originally disabled this to improve security (as you said). But with Microsoft login it has become a technical limitation because I don't know how to log users without using the Microsoft auth web page. I will not close this issue because this feature seems important for people, but I need more time to design this.

Thank you :)

**Comment by sitapea1337** [comment]
I actually thought adding it to Mojang login which is still quite spreadly used.
As for Microsoft, I'm not sure it could be added. Maybe with some browser script, but not sure.

**Comment by mindstorm38** [comment]
Yes you're right, nothing forces me to implement it to MS auth, I will try that 👍

**Comment by intact** [comment]
Probably not worth to implement that feature now.

[Last call to voluntarily migrate Java accounts](https://www.minecraft.net/en-us/article/last-call-voluntarily-migrate-java-accounts)

`Starting March 10, you'll need a Microsoft account to play Java`

**Comment by sitapea1337** [comment]
This might or might not happen. Wouldn't be the first time MS delayed such promises.
Anyways, I'll just implement it to myself, code is quite self explanotary and adding arguments is easy enough job :)

**Comment by mindstorm38** [comment]
Np, feel free :)
