### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by ayunami2000** [mindstorm38/portablemc#7]
In a recent update portablemc lost support for older python3 versions. Can you make it compatible with them? **If it causes too big of an issue then I will update on my end** but it is just a small annoyance.

**Comment by mindstorm38** [comment]
I've not planned to downgrade the script to Python 3.5. Maybe I will do that but for now I think that this version is too old, and some features might be unsupported. Moreover, increasing the range of supported version means increasing de potential count of unknown issues due to difference in the standard library.

I suggest you update your Python version instead and hope you don't mind that too much.

Also, thank you for the support to the project!
